# -*- coding: utf-8 -*-
"""guess_num.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E2jvy0HOJaHYnmd9ejyoRI3pEjw0E9Of
"""

from random import randint
num = randint(1,10)
print(num)

"""# **Final code**"""

rn = 'Random number is: ' + str(num)

user_number = input('Please enter the WHOLE NUMBER ONLY RANGING FROM 1 TO 10: ')
user_enter = 'You entered: ' + user_number

if user_number.isdecimal():
  if int(user_number) <= 10 and int(user_number) >= 1:
    if int(user_number) == int(num):
      print(user_enter)
      print(rn)
      print('Congratulations, You win!🎉🎉🎉')
    else:
      print(user_enter)
      print(rn)
      print('Game over. But You were close.')
  else:
    print(user_enter)
    print(rn)
    print('Game over. Not too close.')
elif user_number.isalpha():
  print(user_enter)
  print(rn)
  print('Game over. Letters are not allowed.')
elif any(let.isalpha() for let in user_number):
  print(user_enter)
  print(rn)
  print('Game over. Mixing letters with numbers is not allowed')
else:
  print(user_enter)
  print(rn)
  print('Game over. Only whole number are allowed.')
